### ISSUE TITLE
how are you dare

### ISSUE THREAD

**Issue by honeyDish** [AlirezaDehlaghi/ICSSIM#4]
those steps installing the tool make no sense

**Comment by AlirezaDehlaghi** [comment]
I could assist you to install it. 
Could you please tell me where is the problem?

**Comment by AlirezaDehlaghi** [comment]
Issue is closed since, I have solved the issue.

**Comment by AlirezaDehlaghi** [comment]
Issue is closed since, I have solved the issue.
