### ISSUE TITLE
how to fix error?

### ISSUE THREAD

**Issue by blueskyfzuds** [AlirezaDehlaghi/ICSSIM#5]
=> ERROR [deployments_plc1 3/7] COPY ./src/ ./src/                                                                                                    0.0s
 => ERROR [deployments_hmi1 3/7] COPY ./src/ ./src/                                                                                                    0.0s
 => ERROR [deployments_hmi2 3/7] COPY ./src/ ./src/                                                                                                    0.0s
------
 > [deployments_plc1 3/7] COPY ./src/ ./src/:
------
------
 > [deployments_hmi1 3/7] COPY ./src/ ./src/:
------
------
 > [deployments_hmi2 3/7] COPY ./src/ ./src/:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref moby::pjl708ce8urrwgaplknukcbyc: "/src": not found

**Comment by AlirezaDehlaghi** [comment]
Hi,

To help you resolve this issue, I require some information:

1. Can you provide details on how you executed this code? Did you run init.sh with or without 'sudo'?
2. Which operating system is your host running on?
3. What version of Docker/Docker-Compose are you currently using?

**Comment by blueskyfzuds** [comment]
i run it in ubantu 22.04, docker v23.03 and docker-composev2.6.1

**Comment by AlirezaDehlaghi** [comment]
But what is the answer for the first question. How did you run this?

**Comment by blueskyfzuds** [comment]
just run sudo ./init.sh

**Comment by AlirezaDehlaghi** [comment]
We will try to simulate the issue and get back to ASAP.

**Comment by ChrisCross1337** [comment]
Reworked the `Dockerfile `and I'm not getting the error from @blueskyfzuds! Looks like pip3 was needed to install pyModbusTCP instead of pip

```

# Base Image
FROM ubuntu:20.04

# Create Directory
RUN mkdir /src

# Copy local directory to container
COPY ./src/ /src/

# Update and install packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && \
    apt-get install -y sudo python3 iputils-ping net-tools git nano python3-pip telnet memcached python3-memcache ettercap-common nmap && \
    pip3 install pyModbusTCP

# Set workdir
WORKDIR /src

```

@AlirezaDehlaghi

**Comment by ChrisCross1337** [comment]
And for the attacker `Dockerfile`, this is the reworked version too 😊:

```
# Base Image
FROM kalilinux/kali-rolling

# Create Directory
RUN mkdir /src

# Copy local directory to container
COPY ./src/ /src/

# Update and install packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && \
    apt-get install -y sudo python3 iputils-ping net-tools git nano python3-pip telnet memcached python3-memcache ettercap-common nmap python3-scapy && \
    pip3 install pyModbusTCP

# Set workdir
WORKDIR /src
```

**Comment by AlirezaDehlaghi** [comment]
> And for the attacker `Dockerfile`, this is the reworked version too 😊:
> 
> ```
> # Base Image
> FROM kalilinux/kali-rolling
> 
> # Create Directory
> RUN mkdir /src
> 
> # Copy local directory to container
> COPY ./src/ /src/
> 
> # Update and install packages
> RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && \
>     apt-get install -y sudo python3 iputils-ping net-tools git nano python3-pip telnet memcached python3-memcache ettercap-common nmap python3-scapy && \
>     pip3 install pyModbusTCP
> 
> # Set workdir
> WORKDIR /src
> ```

Thanks!

**Comment by AlirezaDehlaghi** [comment]
Issue is closed since, we have solved the issue.
