### ISSUE TITLE
Encountered 2 errors during ./init.sh. 

### ISSUE THREAD

**Issue by zodiacRP** [AlirezaDehlaghi/ICSSIM#8]
I had 2 errors during ./init.sh

Error 1: [ DOCKER_COMPOSE BUILD STARTED]

=> [attacker2 3/7] COPY ./src/ ./src/                                     0.0s
 => CANCELED [attacker2 4/7] RUN apt-get update                           34.8s
 => ERROR [hmi1 5/7] RUN DEBIAN_FRONTEND="noninteractive" apt-get install  0.3s
------
 > [hmi1 5/7] RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y tzdata:
0.308 Reading package lists...
0.317 Building dependency tree...
0.317 Reading state information...
0.318 E: Unable to locate package tzdata
------
failed to solve: process "/bin/sh -c DEBIAN_FRONTEND=\"noninteractive\" apt-get install -y tzdata" did not complete successfully: exit code: 100

[ REMOVE TEMP SRC FILE STARTED]

Error 2: [ DOCKER_COMPOSE UP STARTED]
=> CACHED [hmi2 2/7] RUN mkdir src                                        0.0s
 => ERROR [pys 3/7] COPY ./src/ ./src/                                     0.0s
 => ERROR [plc2 3/7] COPY ./src/ ./src/                                    0.0s
 => ERROR [plc1 3/7] COPY ./src/ ./src/                                    0.0s
 => ERROR [hmi3 3/7] COPY ./src/ ./src/                                    0.0s
 => ERROR [hmi1 3/7] COPY ./src/ ./src/                                    0.0s
 => ERROR [hmi2 3/7] COPY ./src/ ./src/                                    0.0s
------
 > [pys 3/7] COPY ./src/ ./src/:
------
------
 > [plc2 3/7] COPY ./src/ ./src/:
------
------
 > [plc1 3/7] COPY ./src/ ./src/:
------
------
 > [hmi3 3/7] COPY ./src/ ./src/:
------
------
 > [hmi1 3/7] COPY ./src/ ./src/:
------
------
 > [hmi2 3/7] COPY ./src/ ./src/:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref 084f2896-55a8-40b1-8fd9-f088a2c3c502::7k3ht24gmvjxd3sv5u1g0grlo: "/src": not found

**Comment by AlirezaDehlaghi** [comment]
Please pull and run the init.sh file again. And let me know the Error still exist.

**Comment by zodiacRP** [comment]
great it works. Thank you and just some minor further edits in the files. Will be playing around with it.
1. init.sh : docker-compose command need to switch to docker compose as the command code had error.
2. docker-compose.yml : ttyl had duplicates in lines 103 onwards. Had to removed them before the initialization works.
