### ISSUE TITLE
./init.sh doesn't work

### ISSUE THREAD

**Issue by Givaa** [AlirezaDehlaghi/ICSSIM#9]
Attaching to attacker, attackermachine, attackerremote, hmi1, hmi2, hmi3, plc1, plc2, pys
pys              | Starting memcached: memcached.
pys              | Traceback (most recent call last):
pys              |   File "FactorySimulation.py", line 78, in <module>
pys              |     factory = FactorySimulation()
pys              |   File "FactorySimulation.py", line 9, in __init__
pys              |     super().__init__('Factory', Connection.CONNECTION, 100)
pys              |   File "/src/ics_sim/Device.py", line 236, in __init__
pys              |     Runnable.__init__(self, name, loop)
pys              |   File "/src/ics_sim/Device.py", line 87, in __init__
pys              |     self._initialize_logger()
pys              |   File "/src/ics_sim/Device.py", line 94, in _initialize_logger
pys              |     self._logger = self.setup_logger(
pys              |   File "/src/ics_sim/Device.py", line 115, in setup_logger
pys              |     handler = logging.FileHandler(file_path, mode=write_mode)
pys              |   File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
pys              |     StreamHandler.__init__(self, self._open())
pys              |   File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
pys              |     return open(self.baseFilename, self.mode, encoding=self.encoding)
pys              | FileNotFoundError: [Errno 2] No such file or directory: '/src/logs/logs-Factory.log'
hmi2             | Traceback (most recent call last):
hmi2             |   File "HMI2.py", line 85, in <module>
hmi2             |     hmi2 = HMI2()
hmi2             |   File "HMI2.py", line 11, in __init__
hmi2             |     super().__init__('HMI2', TAG.TAG_LIST, Controllers.PLCs)
hmi2             |   File "/src/ics_sim/Device.py", line 411, in __init__
hmi2             |     DcsComponent.__init__(self, name, tags, plcs, loop)
hmi2             |   File "/src/ics_sim/Device.py", line 242, in __init__
hmi2             |     Runnable.__init__(self, name,  loop)
hmi2             |   File "/src/ics_sim/Device.py", line 87, in __init__
hmi2             |     self._initialize_logger()
hmi2             |   File "/src/ics_sim/Device.py", line 94, in _initialize_logger
hmi2             |     self._logger = self.setup_logger(
hmi2             |   File "/src/ics_sim/Device.py", line 115, in setup_logger
hmi2             |     handler = logging.FileHandler(file_path, mode=write_mode)
hmi2             |   File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
hmi2             |     StreamHandler.__init__(self, self._open())
hmi2             |   File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
hmi2             |     return open(self.baseFilename, self.mode, encoding=self.encoding)
hmi2             | FileNotFoundError: [Errno 2] No such file or directory: '/src/logs/logs-HMI2.log'
attackerremote   | Traceback (most recent call last):
attackerremote   |   File "AttackerRemote.py", line 96, in <module>
attackerremote   |     attackerRemote = AttackerRemote()
attackerremote   |   File "AttackerRemote.py", line 18, in __init__
attackerremote   |     AttackerBase.__init__(self, 'attacker_remote')
attackerremote   |   File "/src/AttackerBase.py", line 16, in __init__
attackerremote   |     Runnable.__init__(self, name1, 100)
attackerremote   |   File "/src/ics_sim/Device.py", line 87, in __init__
attackerremote   |     self._initialize_logger()
attackerremote   |   File "/src/ics_sim/Device.py", line 94, in _initialize_logger
attackerremote   |     self._logger = self.setup_logger(
attackerremote   |   File "/src/ics_sim/Device.py", line 115, in setup_logger
attackerremote   |     handler = logging.FileHandler(file_path, mode=write_mode)
attackerremote   |   File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
pys exited with code 1
attackerremote   |     StreamHandler.__init__(self, self._open())
attackerremote   |   File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
attackerremote   |     return open(self.baseFilename, self.mode, encoding=self.encoding)
attackerremote   | FileNotFoundError: [Errno 2] No such file or directory: '/src/logs/logs-attacker_remote.log'
hmi1             | Traceback (most recent call last):
hmi1             |   File "HMI1.py", line 135, in <module>
hmi1             |     hmi1 = HMI1()
hmi1             |   File "HMI1.py", line 10, in __init__
hmi1             |     super().__init__('HMI1', TAG.TAG_LIST, Controllers.PLCs, 500)
hmi1             |   File "/src/ics_sim/Device.py", line 411, in __init__
hmi1             |     DcsComponent.__init__(self, name, tags, plcs, loop)
hmi1             |   File "/src/ics_sim/Device.py", line 242, in __init__
hmi1             |     Runnable.__init__(self, name,  loop)
hmi1             |   File "/src/ics_sim/Device.py", line 87, in __init__
hmi1             |     self._initialize_logger()
hmi1             |   File "/src/ics_sim/Device.py", line 94, in _initialize_logger
hmi1             |     self._logger = self.setup_logger(
hmi1             |   File "/src/ics_sim/Device.py", line 115, in setup_logger
hmi1             |     handler = logging.FileHandler(file_path, mode=write_mode)
hmi1             |   File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
hmi1             |     StreamHandler.__init__(self, self._open())
hmi1             |   File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
hmi1             |     return open(self.baseFilename, self.mode, encoding=self.encoding)
hmi1             | FileNotFoundError: [Errno 2] No such file or directory: '/src/logs/logs-HMI1.log'
hmi3             | Traceback (most recent call last):
hmi3             |   File "HMI3.py", line 66, in <module>
hmi3             |     hmi3= HMI3()
hmi3             |   File "HMI3.py", line 13, in __init__
hmi3             |     super().__init__('HMI3', TAG.TAG_LIST, Controllers.PLCs)
hmi3             |   File "/src/ics_sim/Device.py", line 411, in __init__
hmi3             |     DcsComponent.__init__(self, name, tags, plcs, loop)
hmi3             |   File "/src/ics_sim/Device.py", line 242, in __init__
hmi3             |     Runnable.__init__(self, name,  loop)
hmi3             |   File "/src/ics_sim/Device.py", line 87, in __init__
hmi3             |     self._initialize_logger()
hmi3             |   File "/src/ics_sim/Device.py", line 94, in _initialize_logger
hmi3             |     self._logger = self.setup_logger(
hmi3             |   File "/src/ics_sim/Device.py", line 115, in setup_logger
hmi3             |     handler = logging.FileHandler(file_path, mode=write_mode)
hmi3             |   File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
hmi3             |     StreamHandler.__init__(self, self._open())
hmi3             |   File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
hmi3             |     return open(self.baseFilename, self.mode, encoding=self.encoding)
hmi3             | FileNotFoundError: [Errno 2] No such file or directory: '/src/logs/logs-HMI3.log'
plc1             | Traceback (most recent call last):
plc1             |   File "PLC1.py", line 37, in <module>
plc1             |     plc1 = PLC1()
plc1             |   File "PLC1.py", line 10, in __init__
plc1             |     super().__init__(1, sensor_connector, actuator_connector, TAG.TAG_LIST, Controllers.PLCs)
plc1             |   File "/src/ics_sim/Device.py", line 289, in __init__
plc1             |     DcsComponent.__init__(self, name, tags, plcs, loop)
plc1             |   File "/src/ics_sim/Device.py", line 242, in __init__
plc1             |     Runnable.__init__(self, name,  loop)
plc1             |   File "/src/ics_sim/Device.py", line 87, in __init__
plc1             |     self._initialize_logger()
plc1             |   File "/src/ics_sim/Device.py", line 94, in _initialize_logger
plc1             |     self._logger = self.setup_logger(
plc1             |   File "/src/ics_sim/Device.py", line 115, in setup_logger
plc1             |     handler = logging.FileHandler(file_path, mode=write_mode)
plc1             |   File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
plc1             |     StreamHandler.__init__(self, self._open())
plc1             |   File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
plc1             |     return open(self.baseFilename, self.mode, encoding=self.encoding)
plc1             | FileNotFoundError: [Errno 2] No such file or directory: '/src/logs/logs-PLC1.log'
hmi2 exited with code 1
attackerremote exited with code 1
hmi1 exited with code 1
attacker         | Traceback (most recent call last):
attacker         |   File "Attacker.py", line 50, in <module>
attacker         |     attacker = Attacker()
attacker         |   File "Attacker.py", line 7, in __init__
attacker         |     AttackerBase.__init__(self, 'attacker')
attacker         |   File "/src/AttackerBase.py", line 16, in __init__
attacker         |     Runnable.__init__(self, name1, 100)
attacker         |   File "/src/ics_sim/Device.py", line 87, in __init__
attacker         |     self._initialize_logger()
attacker         |   File "/src/ics_sim/Device.py", line 94, in _initialize_logger
attacker         |     self._logger = self.setup_logger(
attacker         |   File "/src/ics_sim/Device.py", line 115, in setup_logger
attacker         |     handler = logging.FileHandler(file_path, mode=write_mode)
attacker         |   File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
attacker         |     StreamHandler.__init__(self, self._open())
attacker         |   File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
attacker         |     return open(self.baseFilename, self.mode, encoding=self.encoding)
attacker         | FileNotFoundError: [Errno 2] No such file or directory: '/src/logs/logs-attacker.log'
hmi3 exited with code 1
plc2             | Traceback (most recent call last):
plc2             |   File "PLC2.py", line 29, in <module>
plc2             |     plc2 = PLC2()
plc2             |   File "PLC2.py", line 12, in __init__
plc2             |     super().__init__(2, sensor_connector, actuator_connector, TAG.TAG_LIST, Controllers.PLCs)
plc2             |   File "/src/ics_sim/Device.py", line 289, in __init__
plc2             |     DcsComponent.__init__(self, name, tags, plcs, loop)
plc2             |   File "/src/ics_sim/Device.py", line 242, in __init__
plc2             |     Runnable.__init__(self, name,  loop)
plc2             |   File "/src/ics_sim/Device.py", line 87, in __init__
plc2             |     self._initialize_logger()
plc2             |   File "/src/ics_sim/Device.py", line 94, in _initialize_logger
plc2             |     self._logger = self.setup_logger(
plc2             |   File "/src/ics_sim/Device.py", line 115, in setup_logger
plc2             |     handler = logging.FileHandler(file_path, mode=write_mode)
plc2             |   File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
plc2             |     StreamHandler.__init__(self, self._open())
plc2             |   File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
plc2             |     return open(self.baseFilename, self.mode, encoding=self.encoding)
plc2             | FileNotFoundError: [Errno 2] No such file or directory: '/src/logs/logs-PLC2.log'
plc1 exited with code 1
attackermachine  | Traceback (most recent call last):
attackermachine  |   File "AttackerMachine.py", line 68, in <module>
attackermachine  |     attackerMachine = AttackerMachine()
attackermachine  |   File "AttackerMachine.py", line 13, in __init__
attackermachine  |     AttackerBase.__init__(self, 'attacker_machine')
attackermachine  |   File "/src/AttackerBase.py", line 16, in __init__
attackermachine  |     Runnable.__init__(self, name1, 100)
attackermachine  |   File "/src/ics_sim/Device.py", line 87, in __init__
attackermachine  |     self._initialize_logger()
attackermachine  |   File "/src/ics_sim/Device.py", line 94, in _initialize_logger
attackermachine  |     self._logger = self.setup_logger(
attackermachine  |   File "/src/ics_sim/Device.py", line 115, in setup_logger
attackermachine  |     handler = logging.FileHandler(file_path, mode=write_mode)
attackermachine  |   File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
attackermachine  |     StreamHandler.__init__(self, self._open())
attackermachine  |   File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
attackermachine  |     return open(self.baseFilename, self.mode, encoding=self.encoding)
attackermachine  | FileNotFoundError: [Errno 2] No such file or directory: '/src/logs/logs-attacker_machine.log'
attacker exited with code 1
attackermachine exited with code 1
plc2 exited with code 1
I am currently working on my Master Degree's thesis at Università degli Studi di Salerno. Can you help me?

**Comment by AlirezaDehlaghi** [comment]
Hi, 

I have updated the code. Please test the code and let me know if it solves the issue.

**Comment by Givaa** [comment]
yes, now it works. The script init_sniff.sh doesn't works. I can't sniff the traffic on the interface because it fails on -i br_icsnet. It says that the interface doesn't exists.

**Comment by AlirezaDehlaghi** [comment]
If you are utilizing a Docker container, you should be able to monitor traffic on "br_icsnet." By examining the docker-compose.yml file, you'll notice that the ICS network is initially named "icsnet," but Docker often changes this to bridge mode, resulting in "br_icsnet." Keep in mind that on your system, the network name may differ. You can identify it by 'ifconfig' (Linux) or 'ipconfig'(windows) command.

**Comment by Givaa** [comment]
yup, i know that. I'm using your simulator on WSL, i am on windows but on a linux subsystem (Ubuntu). I tried if config on every machine like HMI1/PLC1 and the interfaces are there (eth0 and for the PLC also eth1). On my machine when i type ifconfig i only have docker0 eth0 and loop interfaces. How can i do?

**Comment by AlirezaDehlaghi** [comment]
You need to execute ifconfig on WSL2 (Ubuntu), not on ICS components like HMIs or PLCs. WSL creates multiple containers for HMIs and PLCs, and ...! However, to capture traffic using TCP dump, the code needs to be executed one level above, in your case, on WSL.

You should have Dokcer0, eth0, br_icsnet, and br_phynet.

**Comment by Givaa** [comment]
yup, already done that. No interface found. I also tried br_icsim. Thanks for your work and time ❤️

**Comment by AlirezaDehlaghi** [comment]
I just simulated your environment, and I was able to traffic the network. 

My experiment==>

1) configure WSL (Ubuntu 22.04.3 LTS)
2) install docker 
```
curl -fsSL https://get.docker.com -o get-docker.sh
 sudo sh get-docker.sh
```
3) install docker-compose
```
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
 sudo chmod +x /usr/local/bin/docker-compose
```
4) Clone ICSSIM
5) run script ('init_sniff.sh')

**Comment by Givaa** [comment]
Doesn't work :(
I tried reinstalling docker and doesn't work. I followed your instructions.
Thanks anyway!

**Comment by AlirezaDehlaghi** [comment]
It seems unusual. If you're using WSL V2, it should function similarly. I'm sorry, but I can't think of any other reasons without additional information. Please feel free to share and continue this thread if you discover something that might help resolve the issue.

**Comment by Givaa** [comment]
It's very strange, i tried on my mac and doesn't work either. I don't know. If you type ifconfig on your WSL terminal what interfaces shows up?

**Comment by Givaa** [comment]
Hi Alireza! I managed to solve this. I've used EdgeShark (https://edgeshark.siemens.io/#/) that creates a container inside the network and it's able to sniff the traffic with WireShark. It's more practical than tcpdump because it has a GUI. Have a nice day!

**Comment by Givaa** [comment]
Hi Alireza! I managed to solve this. I've used EdgeShark (https://edgeshark.siemens.io/#/) that creates a container inside the network and it's able to sniff the traffic with WireShark. It's more practical than tcpdump because it has a GUI. Have a nice day!
